[package]
name = "quote_streamer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
bus = "2.4.1"
quote_generator_lib = { path = "../quote_generator_lib" }
chrono = "0.4"

